import json
from pathlib import Path
from backend.ingestion.schemas import EvaluationMetrics


class ReportGenerator:
    """Generates machine-readable and human-readable evaluation reports."""

    def format_currency_diff(self, val: float) -> str:
        if val > 0:
            return f"+₹{val:,.2f}"
        elif val < 0:
            return f"-₹{abs(val):,.2f}"
        else:
            return "₹0.00"

    def format_pct_diff(self, val: float) -> str:
        if val > 0:
            return f"+{val:.2f}%"
        elif val < 0:
            return f"{val:.2f}%"
        else:
            return "0.00%"

    def generate_reports(
        self, metrics: EvaluationMetrics, output_dir: str = "data/evaluation"
    ) -> tuple[str, str]:
        Path(output_dir).mkdir(parents=True, exist_ok=True)

        json_path = str(Path(output_dir) / "evaluation_summary.json")
        md_path = str(Path(output_dir) / "evaluation_report.md")

        # Save JSON
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(metrics.model_dump(mode="json"), f, indent=2)

        inc_curr_str = self.format_currency_diff(metrics.incremental_recovery_amount)
        rec_rate_diff = (metrics.recovery_rate - metrics.baseline_recovery_rate) * 100.0
        inc_rate_str = self.format_pct_diff(rec_rate_diff)
        lift_str = self.format_pct_diff(metrics.incremental_recovery_lift_pct)

        # Generate Markdown
        md_content = f"""# RevenueGuard Evaluation Report

## Summary Comparison: Fixed Baseline vs. RevenueGuard

| Metric | Fixed Baseline | RevenueGuard AI Agent | Incremental Difference |
|---|---|---|---|
| **Total Transactions Tested** | {metrics.total_transactions} | {metrics.total_transactions} | - |
| **Total Revenue at Risk** | ₹{metrics.total_at_risk_amount:,.2f} | ₹{metrics.total_at_risk_amount:,.2f} | - |
| **Baseline Recovered Revenue** | ₹{metrics.baseline_recovered_amount:,.2f} | - | - |
| **Automated Recovered Revenue** | - | ₹{metrics.revenueguard_automated_recovered_amount:,.2f} | - |
| **Human-Approved Recovered Revenue** | - | ₹{metrics.revenueguard_human_approved_recovered_amount:,.2f} | - |
| **Total Recovered Revenue** | ₹{metrics.baseline_recovered_amount:,.2f} | ₹{metrics.total_recovered_amount:,.2f} | **{inc_curr_str}** |
| **Recovery Rate** | {metrics.baseline_recovery_rate * 100:.2f}% | {metrics.recovery_rate * 100:.2f}% | **{inc_rate_str}** |
| **Recovery Uplift** | - | **{lift_str}** | - |
| **Net Recovery (After Costs/Friction)** | - | ₹{metrics.net_recovery:,.2f} | - |
| **Interventions Performed** | - | {metrics.intervention_count} | - |
| **Action Operating Costs** | - | ₹{metrics.total_action_cost:,.2f} | - |
| **Customer Contact Count** | - | {metrics.contact_count} | - |
| **Escalations** | - | {metrics.escalation_count} | - |
| **Approval-Required Actions** | - | {metrics.approval_required_count} | - |
| **Approved Approvals** | - | {metrics.approval_approved_count} | - |
| **Denied Approvals** | - | {metrics.approval_denied_count} | - |
| **Policy Denied Actions** | - | {metrics.policy_denied_count} | - |
| **Unsafe Actions Blocked** | - | {metrics.unsafe_actions_blocked} | - |

---
*Report automatically generated by RevenueGuard Evaluation Engine.*
"""

        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        return json_path, md_path
